<a href="https://colab.research.google.com/github/binaria010/Mate2B/blob/main/Clase8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Métodos de Jacobi y Gauss Seidel

Que vamos a ver?



*   Trabajamos con matrices en numpy
*   Jacobi
*   Gauss Seidel



## Matrices en numpy:

In [ ]:
import numpy as np

In [50]:
A = np.array([[1,2,3],[4,-5,5],[7,3,8]])
print(A)

[[ 1  2  3]
 [ 4 -5  5]
 [ 7  3  8]]


In [ ]:
A.shape   # me da una tupla con las dimensiones de A

(3, 3)

In [51]:
d = np.diag(A)  # me devuelve un vector cuyas componentes son los elementos de la diagonal de A
print(d)

[ 1 -5  8]


In [52]:
D = np.diag(d) # me construye una matriz diagonal con entradas los elementos de d
print(D)

[[ 1  0  0]
 [ 0 -5  0]
 [ 0  0  8]]


inversa de una matriz

In [ ]:
Dinv = np.linalg.inv(D) # calcula la inversa de una matriz.

print(Dinv)


[[ 1.     0.     0.   ]
 [-0.    -0.2   -0.   ]
 [ 0.     0.     0.125]]


In [53]:
# otra forma para el caso de matrices diagonales es invertir coordenada a coordenada 
dinv = 1/d
Diinv = np.diag(dinv)

print(Diinv)

[[ 1.     0.     0.   ]
 [ 0.    -0.2    0.   ]
 [ 0.     0.     0.125]]


multiplicacion de matrices

In [ ]:
np.dot(Dinv, A)# esto es la multiplicacion de matrices de algebra  que aprendimos. Sirve para multiplicar matriz con vector

array([[ 1.   ,  2.   ,  3.   ],
       [-0.8  ,  1.   , -1.   ],
       [ 0.875,  0.375,  1.   ]])

In [ ]:
Dinv@A   # otra forma de hacer la multiplicacion. prefiero np.dot!

array([[ 1.   ,  2.   ,  3.   ],
       [-0.8  ,  1.   , -1.   ],
       [ 0.875,  0.375,  1.   ]])

In [ ]:
Dinv * A  # esto es la multiplicacion coordenada a coordenada. En algebra no se usa mucho, en otros lugares si!

array([[ 1.,  0.,  0.],
       [-0.,  1., -0.],
       [ 0.,  0.,  1.]])

Vectores:

In [ ]:
v = np.array([1,2,3])

print(v)
print(v.shape)

[1 2 3]
(3,)


multipliquemos D con v

In [ ]:
print("D =\n" , D, "por  v=", v, " es \n\n", np.dot(D, v))


D =
 [[ 1  0  0]
 [ 0 -5  0]
 [ 0  0  8]] por  v= [1 2 3]  es 

 [  1 -10  24]


In [ ]:
w = np.array([[1,2,3,4]])
print(w.shape)

(1, 4)


In [ ]:
z = np.array([[1], [2], [3],[4]])
print(z)
print(z.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [ ]:
w1 = z.reshape((4,1))
print(w1)
print(w1.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [ ]:
# reshape(-1) convierte a vector fila o columna segun sea el caso:

z1 = z.reshape(-1)
print(z1)
print(z1.shape)

[1 2 3 4]
(4,)


norma de un vector:

In [ ]:
np.linalg.norm(z1)  #calcula la norma euclidea del vector...hay otras normas posibles

5.477225575051661

## Jacobi:

El metodo consiste en obtener una sucesion de vectores $\{x^{(k)}\}$ que converge a la solucion de $Ax =b$ donde $A\in\ R^{n\times n}$, $x,b\in R^{n\times 1}$.

el criterio de parada es que el tamaño relativo de la diferencia de dos sucesivos sea menor que una cierta tolerancia tol dada como input por el usuario, es decir:

$$
\frac{||x^{(k)} - x^{(k-1)}||_{2}}{||x^{(k)}||_{2}} = \frac{\displaystyle\sum_{i=1}^n(x^{(k)}_i - x^{(k-1)}_i)^2}{\displaystyle\sum_{i=1}^n(x^{(k)}_i)^2} < tol
$$


A partir de una aproximacion inicial $x^{(0)}$, la formula para la aproximacion $k$-esima es:

$$
x^{(k)} = D^{-1}(L+U)x^{(k-1)} +D^{-1}b, \qquad k\geq 1
$$

donde $D= diag(A)$ es la matriz diagonal cuyos elementos son los de la diagonal de $A$.

$L$ es la matriz triangular inferior que tiene 0s en la diagonal

$U$ es la matriz triangular superior con 0's en la diagonal

es decir $L+U = A -D$

Pasemos a implementar una rutina (funcion) en python que reciba como inputs: $A$ $b$, $x0$, $tol$ $n=$ numero de iteraciones.


In [54]:
def jacobi(A, b, x0, tol, n =500):

  '''
  esta funcion devuleve una aproximacion x  obtenida mediante el metodo de Jacobi de la solucion de Ax =b.


  inputs:
  A: numpy array de tamanio n x n. La matriz del sistema de ecuaciones
  b: numpy array. Vector fila o columna. puede ser de tamanio (n, ), o (n,1) o (1, n)
  x0: numpy array. Vector fila o columna. puede ser de tamanio (n, ), o (n,1) o (1, n)
  tol: float. tolerancia. De esta forma le indicamo cuando parar
  n: int. maximo numero de iteraciones.
  '''

  d = np.diag(A) #vector con los elementos de la diagonal de A
  D = np.diag(d)  # matriz diagonal con entradas las de d
  Dinv = np.diag(1/d)
  LU = A - D

  # buscamos primera iteracion 
  xold = x0
  xnew = np.dot(Dinv, np.dot(-LU, x0) + b)
  i = 1

  
  while np.linalg.norm(xnew -xold) > tol :
  
    print(" en la iteracion "+ str(i)+ "-esima, x es :", xnew)
    i = i + 1

    #seteo como x anterior al ultimo calculado
    xold = xnew
    
    #calculo un nuevo x
    xnew = np.dot(Dinv, np.dot(-LU, xold) + b)


    if i > n:
      print("despues de "+ str(n) + " pasos no se llegó a una aproximacion deseada")
      break
  
  return(i, xnew)



In [ ]:
#@title
# version mejorada

def Jacobi(A, b, x0, tol, n =500):

  '''
  esta funcion devuleve una aproximacion x  obtenida mediante el metodo de Jacobi de la solucion de Ax =b.


  inputs:
  A: numpy array de tamanio n x n. La matriz del sistema de ecuaciones
  b: numpy array. Vector fila o columna. puede ser de tamanio (n, ), o (n,1) o (1, n)
  x0: numpy array. Vector fila o columna. puede ser de tamanio (n, ), o (n,1) o (1, n)
  tol: float. tolerancia. De esta forma le indicamo cuando parar
  n: int. maximo numero de iteraciones.
  '''

  d = np.diag(A) #vector con los elementos de la diagonal de A
  D = np.diag(d)  # matriz diagonal con entradas las de d
  
  LU = A - D

  # buscamos primera iteracion 
  xold = x0
  xnew = np.linalg.solve(D, np.dot(-LU, x0) + b)
  i = 0

  
  while np.linalg.norm(xnew -xold) >= tol :
  
    print(" en la iteracion "+ str(i)+ "-esima, x es :", xnew)
    i = i + 1

    #seteo como x anterior al ultimo calculado
    xold = xnew
    
    #calculo un nuevo x
    xnew = np.linalg.solve(D, np.dot(-LU, x0) + b)


    if i > n:
      print("despues de "+ str(n) + " pasos no se llegó a una aproximacion deseada")
      break
  
  return(i, xnew)

Vamos con el ejemplo:

$$
\begin{align}
10x_1 -x_2 +2x_3 ~~ &= 6\\
-x_1 +11x_2 -x_3 +3x_4 &= 25\\
2x_1 -x_2 +10x_3 -x_4 &= -11\\
~~   3x_2 - x_3 + 8x_4 &= 15
\end{align}
$$


In [55]:
A = np.array([[10, -1, 2, 0], [-1, 11, -1, 3], [2, -1, 10, -1], [0, 3, -1, 8]])
b = np.array([6, 25, -11, 15])
print("A = ", A, "\n\n b = ", b)

A =  [[10 -1  2  0]
 [-1 11 -1  3]
 [ 2 -1 10 -1]
 [ 0  3 -1  8]] 

 b =  [  6  25 -11  15]


In [56]:
D = np.diag(np.diag(A))

print(D)

[[10  0  0  0]
 [ 0 11  0  0]
 [ 0  0 10  0]
 [ 0  0  0  8]]


In [57]:
LU = A - D

print(-LU) # antes de pasar a dividir por los coeficientes

[[ 0  1 -2  0]
 [ 1  0  1 -3]
 [-2  1  0  1]
 [ 0 -3  1  0]]


In [59]:
Dinv = np.diag(1/np.diag(A))
print("D^{-1}b = ",Dinv)

D^{-1}b =  [[0.1        0.         0.         0.        ]
 [0.         0.09090909 0.         0.        ]
 [0.         0.         0.1        0.        ]
 [0.         0.         0.         0.125     ]]


In [ ]:
x0 = np.array([0,0,0,0])


In [60]:
  # otra forma es: 
x0 =np.zeros(4)

In [61]:
jacobi(A, b, x0, tol =1e-8)

 en la iteracion 1-esima, x es : [ 0.6         2.27272727 -1.1         1.875     ]
 en la iteracion 2-esima, x es : [ 1.04727273  1.71590909 -0.80522727  0.88522727]
 en la iteracion 3-esima, x es : [ 0.93263636  2.05330579 -1.04934091  1.13088068]
 en la iteracion 4-esima, x es : [ 1.01519876  1.95369576 -0.96810863  0.97384272]
 en la iteracion 5-esima, x es : [ 0.9889913   2.01141473 -1.0102859   1.02135051]
 en la iteracion 6-esima, x es : [ 1.00319865  1.99224126 -0.99452174  0.99443374]
 en la iteracion 7-esima, x es : [ 0.99812847  2.00230688 -1.00197223  1.00359431]
 en la iteracion 8-esima, x es : [ 1.00062513  1.9986703  -0.99903558  0.99888839]
 en la iteracion 9-esima, x es : [ 0.99967415  2.00044767 -1.00036916  1.00061919]
 en la iteracion 10-esima, x es : [ 1.0001186   1.99976795 -0.99982814  0.99978598]
 en la iteracion 11-esima, x es : [ 0.99994242  2.00008477 -1.00006833  1.0001085 ]
 en la iteracion 12-esima, x es : [ 1.00002214  1.99995896 -0.99996916  0.99995967]
 

(24, array([ 1.,  2., -1.,  1.]))

El solver de ecuaciones lineales de python nos da:

In [62]:
np.linalg.solve(A,b)

array([ 1.,  2., -1.,  1.])

## Gauss- Seidel

la iteración k-esima es:

$$
x^{(k)} = (D + L)^{-1}(-Ux^{(k-1)}) +(D + L)^{-1}b
$$

donde se inicializa $x0$ como antes y el criterio de parada es de acuerdo a la norma de la diferencia.


Para obener las matrices $L,U$ triangular inferior y superior de $A$ usemos las funciones de numpy: `numpy.tril`, `numpy.triu`

In [ ]:
print("L = \n", np.tril(A))   # Parte abajo de la diagonal. Agregamos la opción -1 para que no incluya a la diagonal
print("U = \n", np.triu(A, +1))   # Parte arriba de la diagonal. Agregamos la opción +1 para que no incluya a la diagonal


L = 
 [[10  0  0  0]
 [-1 11  0  0]
 [ 2 -1 10  0]
 [ 0  3 -1  8]]
U = 
 [[ 0 -1  2  0]
 [ 0  0 -1  3]
 [ 0  0  0 -1]
 [ 0  0  0  0]]


In [63]:
def gauss_seidel(A, b, x0, tol, n=500):
  '''
  esta funcion devuleve una aproximacion x  obtenida mediante el metodo de Gauss-Seidel de la solucion de Ax =b.


  inputs:
  A: numpy array de tamanio n x n. La matriz del sistema de ecuaciones
  b: numpy array. Vector fila o columna. puede ser de tamanio (n, ), o (n,1) o (1, n)
  x0: numpy array. Vector fila o columna. puede ser de tamanio (n, ), o (n,1) o (1, n)
  tol: float. tolerancia. De esta forma le indicamo cuando parar
  '''

  d = np.diag(A) #vector con los elementos de la diagonal de A
  D = np.diag(d)  # matriz diagonal con entradas las de d

  # las matrices L y U:
 
  L = np.tril(A, -1)
  U = np.triu(A, +1)

  #DLinv = np.linalg.inv(D + L)  #esto no lo hacemos

  # buscamos primera iteracion 
  xold = x0
  xnew = np.linalg.solve(D+L, np.dot(-U, xold) + b)
  i = 1

  
  while np.linalg.norm(xnew -xold) > tol :
  
    print(" en la iteracion "+ str(i)+ "-esima, x es :", xnew)
    i = i + 1

    #seteo como x anterior al ultimo calculado
    xold = xnew
    
    #calculo un nuevo x
    xnew = np.linalg.solve(D + L, np.dot(-U, xold) + b) 


    if i > n:
      print("despues de "+ str(n) + " pasos no se llegó a una aproximacion deseada")
      break
  
  return(i, xnew)





In [64]:
A = np.array([[10, -1, 2, 0], [-1, 11, -1, 3], [2, -1, 10, -1], [0, 3, -1, 8]])
b = np.array([6, 25, -11, 15])
x0 = np.zeros(4)


gauss_seidel(A, b, x0, tol = 1e-4)

 en la iteracion 1-esima, x es : [ 0.6         2.32727273 -0.98727273  0.87886364]
 en la iteracion 2-esima, x es : [ 1.03018182  2.03693802 -1.0144562   0.98434122]
 en la iteracion 3-esima, x es : [ 1.00658504  2.00355502 -1.00252738  0.99835095]
 en la iteracion 4-esima, x es : [ 1.00086098  2.00029825 -1.00030728  0.99984975]
 en la iteracion 5-esima, x es : [ 1.00009128  2.00002134 -1.00003115  0.9999881 ]


(6, array([ 1.00000836,  2.00000117, -1.00000275,  0.99999922]))

### Observacion
En este ejemplo el metodo de Gauss -Seidel llego mas rapido que Jacobi, sin embargo esto no siempre es asi. Hay sistemas para los que Gauss -Seidel no converge y Jacobi si.


In [ ]:
A2 = np.array([[1, 2, -2], [1, 1, 1], [2, 2, 1]])
b2 = np.array([7,2,5])
x0 = np.zeros(3)


In [ ]:
# con jacobi:

jacobi(A2, b2, x0, tol = 1e-5)

 en la iteracion 0-esima, x es : [7. 2. 5.]
 en la iteracion 1-esima, x es : [ 13. -10. -13.]
 en la iteracion 2-esima, x es : [ 1.  2. -1.]


(3, array([ 1.,  2., -1.]))

In [ ]:
gauss_seidel(A2, b2, x0, tol= 1e-5)

 en la iteracion 0-esima, x es : [ 7. -5.  1.]
 en la iteracion 1-esima, x es : [ 19. -18.   3.]
 en la iteracion 2-esima, x es : [ 49. -50.   7.]
 en la iteracion 3-esima, x es : [ 121. -126.   15.]
 en la iteracion 4-esima, x es : [ 289. -302.   31.]
 en la iteracion 5-esima, x es : [ 673. -702.   63.]
 en la iteracion 6-esima, x es : [ 1537. -1598.   127.]
 en la iteracion 7-esima, x es : [ 3457. -3582.   255.]
 en la iteracion 8-esima, x es : [ 7681. -7934.   511.]
 en la iteracion 9-esima, x es : [ 16897. -17406.   1023.]
 en la iteracion 10-esima, x es : [ 36865. -37886.   2047.]
 en la iteracion 11-esima, x es : [ 79873. -81918.   4095.]
 en la iteracion 12-esima, x es : [ 172033. -176126.    8191.]
 en la iteracion 13-esima, x es : [ 368641. -376830.   16383.]
 en la iteracion 14-esima, x es : [ 786433. -802814.   32767.]
 en la iteracion 15-esima, x es : [ 1671169. -1703934.    65535.]
 en la iteracion 16-esima, x es : [ 3538945. -3604478.   131071.]
 en la iteracion 17-esima,

(101, array([ 7.83408071e+32, -7.85943372e+32,  5.07060240e+30]))

In [ ]:
np.linalg.solve(A2, b2)

array([ 1.,  2., -1.])