<a href="https://colab.research.google.com/github/binaria010/Mate2B/blob/main/Segunda%20Parte/MinimosCuadrados/Clase%204.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Contenidos:

1. Finalizamos la práctica de regresión lineal haciendo el caso multivariado. 

2. Hacemos una introducción/calentamiento a Componentes principales. 

In [1]:
import numpy as np
import pandas as pd


# Regresion lineal multivariada:




Suponemos que tenemos un conjunto de datos de la forma
$$
({\bf x}_1, y_1), ({\bf x}_2, y_2), \dots, ({\bf x}_N, y_N)
$$

donde ahora cada ${\bf x}_i$ es un vector de digamos $p$ variables ${\bf x} = (x^{(1)}, x^{(2)},\dots, x^{(p)})$ y el indicie $i$ representa la observación i-esima de cada una de ellas.

El objetivo de la regresion multivariada es de nuevo buscar una función lineal de ajuste que ahora depende de estas $p$ variables.

La función es de la forma:

$$
f(x^{(1)}, \dots, x^{(p)}) = b_0 + b_1 x^{(1)} + b_2x^{(2)} + \cdots b_p x^{(p)}
$$

Donde los coeficientes $b_0,~b_1,~\cdots,b_p$ se determinan a partir del conjunto de datos.

Por ejemplo: Consideremos el conjunto de datos Iris:



In [2]:
path_file = "/content/HumanDevelopment.csv"
data = pd.read_csv(path_file, header = 0)


#visualicemos las primeras 10 filas del conjunto de datos
data.head(10)


HDI  LifeExpectancy   MeanYearsofEducation  GNIcapita
0  0.944            81.6                   12.6      64992
1  0.935            82.4                   13.0      42261
2  0.930            83.0                   12.8      56431
3  0.923            80.2                   12.7      44025
4  0.922            81.6                   11.9      45435
5  0.916            80.9                   13.1      43919
6  0.916            80.9                   12.2      39568
7  0.915            79.1                   12.9      52947
8  0.913            82.0                   13.0      42155
9  0.913            81.8                   12.5      32689

PAra este conjunto de datos queremos poder predecir EL HDI (Indice de desarrollo humano) de un país a partir de las variables ```LifeExpectancy```: Esperanza de vida al nacer, ```MeanYearsofEducation```: promedio de anios de eduación formal de los adultos y    ```GNIcapita```: ingreso nacional por habitante en dólares, esta variable está emparentada con el PBI per capita


entonces en este caso:

$$
x^{(1)} = \text{ Life expectancy}
$$
$$
x^{(2)} = \text{Mean years of education}
$$
$$
x^{(3)} = \text{GNI per capita}
$$

y la variable $y$ que es la que pretendemos estimar es $y = \text{HDI}$

Entonces en este caso buscamos una funcion de ajuste

$$
f(x^{(1)}, x^{(2)}, x^{(3)}) = b_0 + b_1* x^{(1)} +b_2*x^{(2)} + b_3* x^{(3)}
$$

usando el conjunto de datos dado.

## Ecuaciones Normales:

En el caso de regresion lineal multivariada las ecuaciones normales que nos permiten determinar los coeficientes son muy similares a las que obtuvimos para regresión por funciones o regresión polinomial. Estas son:

$$
\begin{bmatrix}
b_0 \\ b_1 \\ b_2 \\ \vdots \\ b_p
\end{bmatrix} = (X^T X)^{-1}X^T {\bf y}
$$

donde $X$ es una matriz de tamaño $N \times p+1$ con $N =$ cantidad de observaciones o datos y $p$= cantidad de variables para hacer la regresión.

La matriz $X$ tiene todos unos en la primera columna, en la columna 2 tiene todas las N observaciones de la variable $x^{(1)}$, en la siguiente columna todas las observaciones de la variable $x^{(2)}$ y asi sucesivamente, es decir:

$$
X =\begin{bmatrix}
1 & x^{(1)}_1 & x^{(2)}_1 &\cdots  & x^{(p)}_1\\ 
1 & x^{(1)}_2 & x^{(2)}_2 &\cdots & x^{(p)}_2\\ 
\vdots &\vdots &\vdots & \cdots  & \vdots\\ 
1 & x^{(1)}_N & x^{(2)}_2 &\cdots & x^{(p)}_N
\end{bmatrix}, \qquad  {\bf y} =\begin{bmatrix} y_1\\ y_2 \\ \vdots \\ y_N\end{bmatrix}
$$




Implementemos una rutina que para un conjunto de datos nos devuelva la funcion de ajuste (el output de esta rutina va a ser un objeto función que podemos evaluar.)

In [3]:
def Reg_lineal_multivariada(data_X, data_y):

  """
  data_X = es una matrix de los datos de cada variable: es de tamanio N x p 
  donde N=cantidad de observaciones y p =cantidad de variables a usar
  data_y = es un array de numpy de longitud N

  coefs = [b_0, b_1, ..., b_p]

  f(x) = b_0 +b_1x^{1} + ... +b_p x^{p}
  """
  N , p = data_X.shape  # data_X tiene N filas p columnas

  X = np.ones((N, p+1))   # X es como data_X pero le agregamos los unos al principio

  X[:, 1:] = data_X     #decalramos que de la segunda columna en adelante X y data_X coincidan

  coefs = np.linalg.solve(X.T @ X, X.T @ data_y) # coef

  f = lambda x: coefs[0] + np.dot(coefs[1:], x)
  #print(coefs)

  return f



In [5]:

data_X = data.iloc[:, [1,2,3]]  # seleccionamos las columnas 1, 2,y 3 del dataframe data

data_X.shape   # esto quiere decir que tenemos 195 observaciones de 3 variables


(195, 3)

Convertimos X en un numpy array para manipularlo:

In [6]:
data_X = np.array(data_X)

type(data_X)

numpy.ndarray

In [8]:
data_y = data.iloc[:, 0]
data_y = np.array(data_y)

data_y.shape

(195,)

In [9]:
f = Reg_lineal_multivariada(data_X, data_y)

type(f)

function

Hay que tener en cuenta que el orden de las varaibles de f es el mismo en el que estan en data_X:

Por ejemplo si queremos predecir para un pais con 

$$
\text{LifeExpectancy} = 81.6
$$
$$\text{MeanYearsofEducation} =12.6$$

$$\text{GNIcapita} = 64992
$$

definimos $x = (81.6, 12.6, 64992)$ y calculamos $\hat{y} = f(x)$ donde el sombrerito $\hat{}$  denota la predicción.

In [10]:
x = np.array([81.6, 12.6, 64992])  # en estos valores queremos predecir

print("El HDI para un pais con LifeExp = 81.6, MYofEducation = 12.6 y GNI = 64992 es: \n", 
      f(x))

El HDI para un pais con LifeExp = 81.6, MYofEducation = 12.6 y GNI = 64992 es: 
 0.9603618824237572


si queremos predecir para un pais con 

$$
\text{LifeExpectancy} = 50
$$
$$
\text{MeanYearsofEducation} =10
$$
$$
\text{GNIcapita} = 64992
$$

definimos $x = (50, 10, 64992)$ y calculamos $\hat{y} = f(x)$ donde el sombrerito $\hat{}$  denota la predicción.

In [11]:
x = np.array([50, 10, 64992])

print("El HDI predicho es: ", f(x))

El HDI predicho es:  0.6476247266025903


se nota que aunque el GNI sea igual que antes, influyó el valor de LifeExpecta y de MeanYears of Education

In [12]:
x = np.array([81.6, 10, 64992])

print("El HDI predicho es: ", f(x))

El HDI predicho es:  0.8998179564327845


In [13]:
x = np.array([50, 12.6, 64992])

print("El HDI predicho es: ", f(x))

El HDI predicho es:  0.7081686525935632


Calculamos el $R^2$ de esta regresión:


$$R^2 = \displaystyle\frac{\sum_{i=1}^n(\hat{y_i} - \bar{y})^2}{\sum_{j=1}^n(y_j - y_j)^2}$$

donde $\hat{y_i} = f(x_i)$ el la predicción de $y_i$ usando la función de ajuste $f$.

In [14]:
def R2regmultiple(f, x,y):

  """
  Esta funcion calcula el r^2 de la regresion lineal dados los datos x, y
  """
  
  y_predicho = np.array([f(x[i,:]) for i in range(len(y))])

  avg_y = np.mean(y)

  numerador = np.sum((y_predicho - avg_y)**2)
  denominador = np.sum((y - avg_y)**2)

  return numerador/denominador

In [15]:
r2 = R2regmultiple(f, data_X, data_y)

print("El R^2 de esta regresion es:", r2)

El R^2 de esta regresion es: 0.9553241223196574


# 2. PCA: una entrada en calor a componentes principales

Dado un conjunto de datos, para empezar este conjunto son N observaciones de dos variables, calculamos la matriz de covarianza/correlacion y sus autovalores y autovectores (componnentes principales)




In [17]:
indices = np.random.choice(195, size = 15, replace = False)


In [18]:
X = data_X[indices]
print(X)

[[6.3100e+01 3.8000e+00 3.5600e+03]
 [7.0100e+01 1.2000e+01 2.2352e+04]
 [5.7400e+01 9.9000e+00 1.2122e+04]
 [6.9400e+01 6.4000e+00 1.4003e+04]
 [6.8900e+01 7.6000e+00 9.7880e+03]
 [5.8500e+01 5.2000e+00 3.3630e+03]
 [7.4000e+01 7.5000e+00 1.1449e+04]
 [6.6000e+01 7.8000e+00 2.4340e+03]
 [8.0800e+01 1.1300e+01 4.1187e+04]
 [6.1600e+01 6.3000e+00 2.7620e+03]
 [7.7800e+01 7.9000e+00 9.9940e+03]
 [7.5400e+01 9.3000e+00 1.1780e+04]
 [8.1900e+01 1.1900e+01 3.3890e+04]
 [6.4400e+01 7.8000e+00 1.6367e+04]
 [7.4900e+01 1.2100e+01 7.1640e+03]]


In [19]:
X.shape


(15, 3)

Para este conjunto de 195 observaciones de 3 variables calculemos la matriz de covarianza y de correlacion:

Primero centremos los datos:

In [20]:
# Centramos los datos de cada variable por separado:

x1 = (X[:, 0] - np.mean(X[:, 0]))
x2 = X[:, 1] - np.mean(X[:, 1])
x3 = X[:, 2] - np.mean(X[:, 2])

print("x1 = \n", x1)
print("x2 = \n", x2)
print("x3 = \n", x3)
 
print("----------------------")
print("El promedio de las observaciones de x1 es: ", np.mean(x1))
print("El promedio de las observaciones de x2 es: ", np.mean(x2))
print("El promedio de las observaciones de x3 es: ", np.mean(x3))

x1 = 
 [ -6.51333333   0.48666667 -12.21333333  -0.21333333  -0.71333333
 -11.11333333   4.38666667  -3.61333333  11.18666667  -8.01333333
   8.18666667   5.78666667  12.28666667  -5.21333333   5.28666667]
x2 = 
 [-4.65333333  3.54666667  1.44666667 -2.05333333 -0.85333333 -3.25333333
 -0.95333333 -0.65333333  2.84666667 -2.15333333 -0.55333333  0.84666667
  3.44666667 -0.65333333  3.64666667]
x3 = 
 [ -9921.   8871.  -1359.    522.  -3693. -10118.  -2032. -11047.  27706.
 -10719.  -3487.  -1701.  20409.   2886.  -6317.]
----------------------
El promedio de las observaciones de x1 es:  1.9421501444109406e-14
El promedio de las observaciones de x2 es:  2.9605947323337506e-16
El promedio de las observaciones de x3 es:  0.0


hmmmm deberia haber una forma mas facil de hacerlo que no sea variable por variable...sobre todo si en lugar de 3 variables fueran 15!

In [21]:
# para una matriz donde cada columna representa las observaciones de una variable, si calculamos
np.mean(X, axis = 0)

array([6.96133333e+01, 8.45333333e+00, 1.34810000e+04])

In [22]:
# comparemos con cada una por separado

print(np.mean(X[:,0]))
print(np.mean(X[:,1]))
print(np.mean(X[:,2]))

69.61333333333332
8.453333333333333
13481.0


In [23]:
N = X.shape[0]
X_center = X - np.mean(X, axis = 0)
S = 1/N * X_center.T @ X_center  # esto nos da la matriz de covarianza 

Si quisieramos la matriz de correlacion tendriamos que ademas dividir por los desvios estandar

In [24]:
X_standard = (X - np.mean(X, axis = 0))/np.std(X, axis = 0)

Una vez que estandarizamos los datos (los centramos para que tengan media 0 y los dividimos por sus desvios para que tengan desvio 1) ahora si, podemos definir la matriz de correlacion como

$$
C = \frac{1}{N}X_{\text{standard}}^T X_{\text{standard}}
$$

In [25]:
C = 1/N *X_standard.T @ X_standard

print(C)

[[1.         0.58761334 0.64483391]
 [0.58761334 1.         0.65877381]
 [0.64483391 0.65877381 1.        ]]


El general el algoritmo de PCA (componentes principales) se le aplica ya sea a la matriz de covarianza o a la de correlacion. Nosotros en general se lo vamos a aplicar a la de correlacion, es decir ya los datos los dejamos estandarizados

## Componentes principales:

Para calcular las componentes principales debemos hacer la descomposicion en autovectores de la matriz C o de la S (segun se pida, preferiblemente de la C)

In [26]:
C_eigs = np.linalg.eigh(C)

autovalores = C_eigs[0]

V = C_eigs[1]

In [28]:
print("Los autovalores de C son:", autovalores)

print("----------------\n")

print("Los autovectores de C son: \n", V)



Los autovalores de C son: [0.3255961  0.41309824 2.26130567]
----------------

Los autovectores de C son: 
 [[-0.3507481  -0.74404259 -0.56866193]
 [-0.4799077   0.66425354 -0.57311066]
 [ 0.80415444  0.07188777 -0.59005744]]


Una vez que tenemos la descomposicion espectral (descomposicion en autovectores) de $C$, las compnentes principales se calculan:

$$
Z = V @ X_{\text{standard}} 
$$

La componente principal $i$-esima es la columna i-esima de la matriz $Z$. 

In [29]:
V[:,::-1]  # con esto permuto las columnas la ultima aparezca de primera

array([[-0.56866193, -0.74404259, -0.3507481 ],
       [-0.57311066,  0.66425354, -0.4799077 ],
       [-0.59005744,  0.07188777,  0.80415444]])

In [ ]:
autovalores = autovalores[::-1]

print(autovalores)

[2.28968593 0.48214433 0.22816974]


In [30]:
V = V[:,::-1]   # redefino V para que tenga el orden que quiero

Z = X_standard @ V

In [ ]:
print("la componente principal z1 = \n ", Z[:, 0])

print("\n \nla componente principal z2 = \n ", Z[:, 1])

print("\n\nla componente principal  z3 = \n ", Z[:, 2])

la componente principal z1 = 
  [ 0.14786111 -1.48613868 -0.13118518 -2.76341718 -0.37401839 -0.57408418
 -0.29665597  2.03027038  2.12379926 -0.96964437  1.58816805 -2.48753421
  1.40395198 -0.11814767  1.90677505]

 
la componente principal z2 = 
  [-0.49937147 -0.51718345 -0.85256078  0.42640008 -0.30756621 -0.60134096
 -0.23755494  0.49464046  0.50154423 -0.80064515  0.40656065  1.89064951
  0.24705294 -0.49035611  0.33973121]


la componente principal  z3 = 
  [ 0.24181669 -0.44233487  0.48294969  0.62305096 -0.38629804 -0.08151976
 -0.41565611 -0.23589607  0.00153292  0.16506951 -0.59587839 -0.11615844
 -0.28014668 -0.23794156  1.27741014]
