<a href="https://colab.research.google.com/github/binaria010/Mate2B/blob/main/Segunda%20Parte/PCA%26Clustering/Clase%205.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Componentes principales:



In [27]:
import numpy as np
import pandas as pd

Para calcular las componentes principales debemos hacer la descomposicion en autovectores de la matriz C o de la S (segun se pida, preferiblemente de la C)


## Ejercicio 1:
Los siguientes datos representan las puntuaciones de 10 personas en dos materias diatintas. Queremos para este conjunto de datos dar las componentes principales y elegir la que mejor representa los datos.

In [16]:
p1 = np.array([77.9, 81.3, 66.4, 53.1, 86.9, 69.0, 57.3, 50.3, 69.4, 82.9]).reshape(-1,1)
p2 = np.array([87.3, 89.5, 73.0, 62.0, 96.4, 74.7, 63.5, 70.9, 75.6, 92.4]).reshape(-1,1)

X = np.hstack((p1, p2))

print(X)

[[77.9 87.3]
 [81.3 89.5]
 [66.4 73. ]
 [53.1 62. ]
 [86.9 96.4]
 [69.  74.7]
 [57.3 63.5]
 [50.3 70.9]
 [69.4 75.6]
 [82.9 92.4]]


Estandarizamos los datos:

por columnas calculamos el promedio y los desvios :

In [17]:
X_standar = (X - np.mean(X, axis = 0))/np.std(X, axis = 0)

print(X_standar)

[[ 0.69262179  0.76328397]
 [ 0.97130984  0.95475772]
 [-0.24999958 -0.48129537]
 [-1.34016168 -1.43866409]
 [ 1.43032547  1.55528901]
 [-0.03688518 -0.33333838]
 [-0.99589997 -1.30811381]
 [-1.56966949 -0.66406576]
 [-0.00409835 -0.25500821]
 [ 1.10245716  1.20715493]]


In [18]:
N = X.shape[0]


C = 1/N * (X_standar.T @ X_standar)

print(C)

[[1.         0.94182595]
 [0.94182595 1.        ]]


In [19]:
C_eigs = np.linalg.eigh(C)

autovalores = C_eigs[0]

V = C_eigs[1]

print("los autovalores de C son :", autovalores)
print("\n Los autovectores de C son : V = \n", V)

los autovalores de C son : [0.05817405 1.94182595]

 Los autovectores de C son : V = 
 [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


Notar los autovalores están dados en orden ascendiente (de menor a mayor). Vamos a reordenarlos de tal forma que el primer autovalor sea el mas grande y asi sucesivamente. Lo mismo hacemos con los autovectores, asi la primera columna de V corresponde al autovector de mayor autovalor, la segunda corresponde al  autovalor mas chico


In [20]:
autovalores = autovalores[::-1]

V = V[:, ::-1]

print("los autovalores de C son :", autovalores)
print("\n Los autovectores de C son : V = \n", V)

los autovalores de C son : [1.94182595 0.05817405]

 Los autovectores de C son : V = 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


Ahora definimos las componentes principales:

$$
Z = \begin{bmatrix} |  & | & \cdots  &| \\
z_1  & z_2 & \cdots & z_p\\
|  & | & \cdots  & |
\end{bmatrix} = X_{\text{standar}}V  
$$

In [21]:
Z = X_standar @ V

In [22]:
print("la componente principal z1 = \n ", Z[:, 0])

print("\n \nla componente principal z2 = \n ", Z[:, 1])


la componente principal z1 = 
  [ 1.02948084  1.36193543 -0.51710362 -1.96492655  2.11114824 -0.26178759
 -1.62918377 -1.57948935 -0.18321601  1.63314237]

 
la componente principal z2 = 
  [ 0.04996571 -0.01170412 -0.16355082 -0.06965172  0.08836257 -0.20962407
 -0.22076853  0.64035854 -0.17742006  0.0740325 ]


Vemos mediante regresiones lineales que componentes representan mejor los datos.

In [23]:
def reglineal(x, y):

  """
  Esta funcion calcula los coeficientes de una regresion lineal simple. Devuelve la funcion a + bx 
  Inputs:
  x : numpy array dimension n
  y : numpy array dimension n

  Return:
  f : poly1D: objeto polinomio de python. f es un polinomio de grado 1: alpha* +beta*x
  """
  n = len(x)
  X = np.ones((n,2))

  X[:, 1] = x

  coefs =  np.linalg.solve(X.T @ X, np.dot(X.T, y))

  a = coefs[0]
  b = coefs[1]

  f = np.poly1d([b, a])

  return f

def R2(f, x,y):

  """
  Esta funcion calcula el r^2 de la regresion lineal dados los datos x, y y el ajuste f
  """
  
  y_predicho = f(x)
  avg_y = np.mean(y)

  numerador = np.sum((y_predicho - avg_y)**2)
  denominador = np.sum((y - avg_y)**2)

  return numerador/denominador




In [24]:
# hacemos una regresion lineal de p1 con varaible regresora z1, y otra con varaible regresora z2

fp1_z1 = reglineal(Z[:, 0], X_standar[:,0])
r2p1_z1 = R2(fp1_z1,Z[:, 0], X_standar[:,0])

fp1_z2 = reglineal(Z[:, 1], X_standar[:,0])
r2p1_z2 = R2(fp1_z2,Z[:, 1], X_standar[:,0])



print("los R^2 de las regresiones simples de p1 versus z1, z2 son  \n\n con z1 es = ",
      r2p1_z1, " \n con z2 es = ", r2p1_z2)


los R^2 de las regresiones simples de p1 versus z1, z2 son  

 con z1 es =  0.9709129760488517  
 con z2 es =  0.02908702395114788


In [25]:
# hacemos una regresion lineal de p2 con varaible regresora z1, y otra con varaible regresora z2


fp2_z1 = reglineal(Z[:, 0], X_standar[:,1])
r2p2_z1 = R2(fp2_z1,Z[:, 0], X_standar[:,1])

fp2_z2 = reglineal(Z[:, 1], X_standar[:,1])
r2p2_z2 = R2(fp2_z2,Z[:, 1], X_standar[:,1])



print("los R^2 de las regresiones simples de x_2 versus z1, z2: \n con z1 es = ",
      r2p2_z1, " \n con z2 es = ", r2p2_z2)

los R^2 de las regresiones simples de x_2 versus z1, z2: 
 con z1 es =  0.9709129760488517  
 con z2 es =  0.029087023951148077


Con esto podemos observar  que la información está mayormente representada por la componente $z_1$

Notar que si hacemos la cuenta:

$$
\frac{\lambda_1}{\lambda_1 + \lambda_2} = R^2\text{ de la regresion de }x_1 \text {(o de } x_2 \text{) en función de } z_1 = \text{ proporción de varianza en } x_1 \text{ explicada por }z_1
$$

$$
\frac{\lambda_2}{\lambda_1 + \lambda_2} = R^2\text{ de la regresion de }x_1 \text {(o de } x_2 \text{) en función de } z_2 = \text{ proporción de varianza en } x_1 \text{ explicada por }z_2
$$

In [ ]:
print("proporcion de varianza explicada por la componente z_1 es: ", autovalores[0]/np.sum(autovalores))

print("\nproporcion de varianza explicada por la componente z_2 es: ", autovalores[1]/np.sum(autovalores))

proporcion de varianza explicada por la componente z_1 es:  0.9798341947614037

proporcion de varianza explicada por la componente z_2 es:  0.020165805238596343


Calculemos el *score* de la componente $z_1$ para una persona que tiene puentuaciones $p_1=85$ $p_2 =70$:
llamemos $x = (p_1, p_2)$ al vector de puntuaciones, entonces:

$$
z_1 = \langle v_1, x\rangle = v_1[0]*p_1 + v_1[1]*p_2
$$

donde $v_1$ es el autovector correspondiente al autovalor mas grande y $v_1[0], v_1[1]$ denotan su primera y segunda componente.

In [26]:
x = np.array([85, 70])
score_z1 = np.dot(V[:, 0], x)

print("El score de la primera componente para las observaciones p_1 y p_2 es: ", score_z1)

El score de la primera componente para las observaciones p_1 y p_2 es:  109.60155108391486


## Ejemplo 2:

Volvamos a considerar nuestro conjunto de datos ```HumanDevelopment.csv```. Esta vez vamos a considerarlos todos.

Vamos a determinar las componentes principales de la matriz de correlacion de los datos y vamos a elegir las k componentes mas representativas de acuerdo a cuanta varianza acumulada explicada se desea.


In [28]:
ruta = "/content/HumanDevelopment.csv"

data = pd.read_csv(ruta, header = 0)

X = np.array(data)

print(X[:6, :])  # le digo que me imprima las primeras 6 filas de los datos

[[9.4400e-01 8.1600e+01 1.2600e+01 6.4992e+04]
 [9.3500e-01 8.2400e+01 1.3000e+01 4.2261e+04]
 [9.3000e-01 8.3000e+01 1.2800e+01 5.6431e+04]
 [9.2300e-01 8.0200e+01 1.2700e+01 4.4025e+04]
 [9.2200e-01 8.1600e+01 1.1900e+01 4.5435e+04]
 [9.1600e-01 8.0900e+01 1.3100e+01 4.3919e+04]]


In [29]:
print(X.shape)

(195, 4)


In [30]:
# estandarizamos los datos:

X_standar = (X -  np.mean(X, axis = 0))/np.std(X, axis = 0)

N = X_standar.shape[0]

C = 1/N * X_standar.T @ X_standar

print(C)

[[1.         0.90005818 0.89807827 0.7360487 ]
 [0.90005818 1.         0.73421159 0.62452621]
 [0.89807827 0.73421159 1.         0.57106579]
 [0.7360487  0.62452621 0.57106579 1.        ]]


In [31]:
# Hallamos los autovalores y autovectores de C:

C_eigs = np.linalg.eigh(C)

autovalores = C_eigs[0]

V = C_eigs[1]

print("autovalores son: ", autovalores)

print("\n\nLa matriz de autovectores es V = \n", V)

autovalores son:  [0.03074972 0.26018358 0.46168794 3.24737876]


La matriz de autovectores es V = 
 [[-0.82725488 -0.00107732 -0.12860493 -0.54690857]
 [ 0.36599197 -0.75568083 -0.19931223 -0.5052435 ]
 [ 0.39530001  0.63841331 -0.43505092 -0.49688735]
 [ 0.15949026  0.14619768  0.86860008 -0.44578357]]


Como siempre, obtenemos los autovalores en orden ascendiente pero los queremos en orden descendiente 

In [32]:
#invertimos el orden:

autovalores = autovalores[::-1]
V = V[:, ::-1]

print("autovalores son: ", autovalores)

print("\n\nLa matriz de autovectores es V = \n", V)

autovalores son:  [3.24737876 0.46168794 0.26018358 0.03074972]


La matriz de autovectores es V = 
 [[-0.54690857 -0.12860493 -0.00107732 -0.82725488]
 [-0.5052435  -0.19931223 -0.75568083  0.36599197]
 [-0.49688735 -0.43505092  0.63841331  0.39530001]
 [-0.44578357  0.86860008  0.14619768  0.15949026]]


Definamos las componentes principales:

$$
Z = X@V
$$

donde $X$ es la matriz de los datos ya estandarizados

In [33]:
Z = X@V

In [42]:
var_total = np.sum(autovalores)


In [57]:
i = 0
var_explicada = 0
tope = 0.9  # queremos lograr una varianza explicada acumulada del 90%

while var_explicada < tope:
  
  var_explicada = np.sum(autovalores[:i+1])/var_total
  print("la varianza explicada acumulada es: ", var_explicada)
  i = i+1



la varianza explicada acumulada es:  0.8118446893887954
la varianza explicada acumulada es:  0.9272666744527601


## Ejercicio:
Implementar una rutina en python que reciba como input la ruta de un archivo  y un número $\textit{$p\_acum$}$ y devuelva la mínima cantidad de componentes principales que deben considerarse para que el porcentaje de varianza acumulada sea mayor o igual que $\textit{$p\_acum$}$

## Ejercicio: Resolver hasta ejercicio 6 de la práctica 6.





